name: Deploy to InfinityFree

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug (list files to ensure checkout worked)
      - name: List files (debug)
        run: ls -la

      # Step 3: Deploy via FTP (InfinityFree-specific settings)
      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.infinityfree.net  # InfinityFree's FTP server
          username: ${{ secrets.IF_USERNAME }}  # Your InfinityFree username
          password: ${{ secrets.IF_PASSWORD }}  # Your InfinityFree password
          server-dir: "/htdocs/"  # InfinityFree's root web directory
          local-dir: "./public"   # Deploy Laravel's public folder only
          protocol: ftps          # InfinityFree requires FTPS (not regular FTP)
          port: 21                # Default FTPS port
          dangerous-clean-slate: false  # Don't delete existing files first
          exclude: |
            .git/
            .github/
            node_modules/
            .env
          log-level: verbose      # Detailed error logs
